---
io-services:
  reader:
    class: org.jlab.clas.std.services.convertors.HipoToHipoReader
    name: HipoToHipoReader
  writer:
    class: org.jlab.clas.std.services.convertors.HipoToHipoWriter
    name: HipoToHipoWriter
services:
  #- class: org.jlab.clara.demo.services.FaceDetectorService
  #  name: FaceDetectorService
  - class: SimpleEngine
    name: SimpleEngine
    lang: cpp

mime-types:
  - binary/data-hipo
